{{- if .Values.influxdb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "influxdb.fullname" . }}
  labels:
    {{- include "influxdb.labels" . | nindent 4 }}
spec:
  selector:
    app: influxdb
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
  # Add other necessary configurations for the InfluxDB service
  {{- end }}